jenkins:
  systemMessage: "Welcome to the Hylozoa-Engine Jenkins Instance."
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         name: "admin"
         password: ${USER_ADMIN_PASSWORD}
       - id: dev
         name: "dev"
         password: ${USER_DEV_PASSWORD}
  authorizationStrategy:
    roleBased:
      roles:
        global:
            - name: "admin"
              description: "Admin"
              permissions:
                - "Overall/Administer"
              entries:
              - user: "admin"
            - name: "dev"
              description: "HE Developers"
              permissions:
                - "Overall/Read"
                - "Job/Read"
                - "Job/Build"
                - "Job/Workspace"
                - "Job/Cancel"
              entries:
              - user: "dev"
  unclassified:
  globalNodeProperties:
    - envVars:
        env:
          - key: GIT_SSH_KNOWN_HOSTS
            value: "/var/jenkins_home/.ssh/known_hosts"
tool:
  git:
    installations:
      - name: "Default"
        home: "git"
jobs:
  - file: ./job_dsl.groovy
